import './globals.css'

import type { Metadata } from 'next'
import { Geist, Bricolage_Grotesque, Geist_Mono } from 'next/font/google'

import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/providers/theme-provider'

const fontSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
})

const fontMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
})

const fontHeading = Bricolage_Grotesque({
   variable: '--font-heading',
   subsets: ['latin'],
})

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang='en' suppressHydrationWarning>
         <body
            className={cn(
               'min-h-screen font-sans antialiased',
               fontSans.variable,
               fontHeading.variable,
               fontMono.variable
            )}
         >
            <ThemeProvider
               attribute='class'
               defaultTheme='system'
               enableSystem
               disableTransitionOnChange
            >
               {children}
            </ThemeProvider>
         </body>
      </html>
   )
}
